export const LOAD_ITEM = "LOAD_ITEM"
export const DRAW_LOAD_ITEM = "DRAW_LOAD_ITEM"
export const SUCCESS_LOAD_ITEM = "SUCCESS_LOAD_ITEM"
export const FAILED_LOAD_ITEM = "FAILED_LOAD_ITEM"

export const ADD_ITEM = "ADD_ITEM"
export const DRAW_ADD_ITEM = "DRAW_ADD_ITEM"
export const SUCCESS_ADD_ITEM = "SUCCESS_ADD_ITEM"
export const FAILED_ADD_ITEM = "FAILED_ADD_ITEM"

export const REMOVE_ITEM = "REMOVE_ITEM"
export const DRAW_REMOVE_ITEM = "DRAW_REMOVE_ITEM"
export const SUCCESS_REMOVE_ITEM = "SUCCESS_REMOVE_ITEM"
export const FAILED_REMOVE_ITEM = "FAILED_REMOVE_ITEM"

export const UPDATE_ITEM = "UPDATE_ITEM"
export const DRAW_UPDATE_ITEM = "DRAW_UPDATE_ITEM"
export const SUCCESS_UPDATE_ITEM = "SUCCESS_UPDATE_ITEM"
export const FAILED_UPDATE_ITEM = "FAILED_UPDATE_ITEM"

export const DETAIL_ITEM = "DETAIL_ITEM"

export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const SUCCESS_ADD_TRANSACTION = "SUCCESS_ADD_TRANSACTION"
export const FAILED_ADD_TRANSACTION = "FAILED_ADD_TRANSACTION"